---
title: "Homework_03"
author: "Sandra Nnadi"
date: "2/28/2021"
output: html_document
---


# Regular Expression Puzzles

*For these problems, use your plain text editor (BBedit, Notepad++, or something else) to type in the problem text and use the search function to write a regular expression that gives the desired result. In your homework solution, provide the regular expression that works (there are several ways to solve each problem) within some plain text fencing on your markdown page, and add a bit of markdown text to explain what each element of your regular expression is doing. If you get stuck, give the solution that gets you as close as you can.*


### Puzzle 1

```
\s+
replace with 
\1\2,

```
##### Backslash s+ highlighted the space between words then replace with \1\2, removed the spaces and added a comma after the word.


### Puzzle 2

```
(\w+),\s(\w+),\s(\w+)\s(\w+)\s(\w+)
replace with
\2 \1 [(\3 \4 \5)]

Bryan Ballif [University of Vermont]

```
##### first the pieces i wanted was specified then i used capture to highlight the pieces i wanted to keep. Replacing with \2 space \1 swaps the names and removes the comma. I added a bracket to capture the next three words. this method also worked for the two lines but with some modifications.

```
(\w+),\s(\w+),\s(\w+)\s(\w+)
replace with
\2 \1 [(\3 \4)]

Aaron Ellison [Harvard Forest]
Sydne Record [Bryn Mawr]

```

### Puzzle 3: Place each file name on its own line

```
(\w+)\s(\w+)\s(\w+)(\.*)(\w+)\s
replace with
\1 \2 \3\4\5\n

(\w+)\s(\w+)\s(\w+)\s(\w+)\s(\w+)(\.*)(\w+)\s
replace with
\1 \2 \3 \4 \5\6\7\n

(\w+)\s(\w+)\s(\w+)(\.*)(\w+)\s
replace with
\1 \2 \3\4\5\n

0001 Georgia Horseshoe.mp3
0002 Billy In The Lowground.mp3
0003 Cherokee Shuffle.mp3
0004 Walking Cane.mp3

```
##### Pieces of interest were specified and captured then replaced with the backslash and appropriate number then ending with a line break

### Puzzle 4: Grab the four digit number and place at the end of the title

```
(\w+)\s(\w+)\s(\w+)(\.*)(\w+)
replace with
\2 \3_\1\4\5

(\w+)\s(\w+)\s(\w+)\s(\w+)\s(\w+)(\.*)(\w+)
replace with 
\2 \3 \4 \5_\1\6\7

(\w+)\s(\w+)\s(\w+)(\.*)(\w+)
replace with
\2 \3_\1\4\5

(\w+)\s(\w+)\s(\w+)(\.*)(\w+)
replace with
\2 \3_\1\4\5

Georgia Horseshoe_0001.mp3
Billy In The Lowground_0002.mp3
Cherokee Shuffle_0003.mp3
Walking Cane_0004.mp3

```
### Puzzle 5 : write a single expression to rearrange the dataset

```
(\w)\w*,(\w+),\d+\.\d,(\d*)
replace with
\1_\2,\3

C_pennsylvanicus,44
C_herculeanus,3
M_punctiventris,4
L_neoniger,55

```


### Puzzle 6: rearrange the original data to abbreviate the species name

```
(\w)\w*,(\w)(\w)(\w)(\w)\w*,\d+\.\d,(\d*)
replace with
\1_\2\3\4\5,\6

C_penn,44
C_herc,3
M_punc,4
L_neon,55

```


### Puzzle 7: Fuse the first 3 letters of genus and species name then reverse the numerical data

```
(\w)(\w)(\w)\w*,(\w)(\w)(\w)\w*,(\d+\.\d),(\d*)
replace with
\1\2\3\4\5\6, \8, \7

Campen, 44, 10.2
Camher, 3, 10.5
Myrpun, 4, 12.2
Lasneo, 55, 3.3

```



















